### ISSUE TITLE
Not working with ie11

### ISSUE THREAD

**Issue by Thibka** [vanruesc/postprocessing#102]
Hi,

It seems like the effects do not work on IE11.
I'm working with webpack and whenever I try to import and use a postprocessing class I get a weird syntax error pointing to this beauty:
![capture](https://user-images.githubusercontent.com/4466455/49943083-426adc00-fee7-11e8-8945-af715d4d3143.JPG)
I eventually noticed that when I'm using IE, the demo page doesn't work either.
https://vanruesc.github.io/postprocessing/public/demo/

Is it even supposed to work on IE did you give up on it? :)

Anyway, thanks!

**Comment by vanruesc** [comment]
Hello,

thanks for reporting this issue! I wasn't aware that `postprocessing` doesn't work on IE11, but I'm not surprised.

I know that the demo uses a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) for input handling. Apparently, [Proxies cannot be transpiled or polyfilled](https://babeljs.io/docs/en/learn/#proxies) and [IE11 doesn't support Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Browser_compatibility). So that's the first thing that breaks it in IE.

> I working with webpack and whenever I try to import and use a postprocessing class I get a weird syntax error

Hm, I'm afraid the screenshot doesn't tell me anything. What does the syntax error message say? The `postprocessing` library _should_ work just fine with webpack.

> Is it even supposed to work on IE did you give up on it? :)

I'll look into it and give you a definite answer when I get a chance.

**Comment by Thibka** [comment]
Thanks for answering me so quickly! 
The syntax error message just says there is a syntax error, I'm afraid it's not gonna help :)
I will look into it as soon as possible, and I'll make a simplified example to try to isolate my problem.

**Comment by vanruesc** [comment]
> I will look into it as soon as possible, and I'll make a simplified example to try to isolate my problem.

Thanks, that would help a lot.

I found out that IE11 doesn't fully support `Maps`. One thing you could try to fix `postprocessing` in IE11 on your end is to use the [babel polyfill](https://babeljs.io/docs/en/babel-polyfill).

**Comment by Thibka** [comment]
So I tried to use as few other packages as possible (but still with Webpack), and I still get the syntax error with Internet Explorer 11. 
![capture1](https://user-images.githubusercontent.com/4466455/50378038-1fe46b80-0629-11e9-9269-3bdef287c87b.JPG)
![capture2](https://user-images.githubusercontent.com/4466455/50378028-df84ed80-0628-11e9-9bc5-36139f483f91.JPG)
And not better luck with babel polyfill. 
I wish I could have been of more help :/

**Comment by vanruesc** [comment]
> And not better luck with babel polyfill. I wish I could have been of more help :/

Don't worry about it; I appreciate the effort 👍

The second screenshot you provided shows that your bundle isn't fully transpiled: there's a `class` keyword in that `eval(...)`. Please make sure that your webpack setup uses [Babel](https://babeljs.io/) to transpile your final product into ES5 code. Note that the `postprocessing` library in your `node_modules` directory must not be excluded from that process.

Now to answer your initial question: yes, `postprocessing` works in IE11. I've tested it [here](https://github.com/vanruesc/postprocessing-test-ie11).

![untitled](https://user-images.githubusercontent.com/9214917/50384111-53bea000-06c0-11e9-8027-45a0aa4944b0.png)

At first, I tried to use the babel polyfill with Rollup, but that turned out to be a huge hassle. After reading [this article](https://hackernoon.com/polyfills-everything-you-ever-wanted-to-know-or-maybe-a-bit-less-7c8de164e423), I decided to use [polyfill.io](https://polyfill.io/v2/docs/) instead and had to include `https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es5,es6` to get it to work in IE11 ([reference](https://github.com/Financial-Times/polyfill-service/issues/792#issuecomment-407141158)).

Happy Holidays!

**Comment by Thibka** [comment]
> Note that the `postprocessing` library in your `node_modules` directory must not be excluded from that process.

Good heavens it works!
I was indeed excluding the whole node_modules directory from the babel loader. 
Thanks for your support and happy holidays to you too :)
