### ISSUE TITLE
Cannot access material property in ShaderPass

### ISSUE THREAD

**Issue by KholofeloMoyaba** [vanruesc/postprocessing#107]
I used to be able to access and manipulate the ShaderPass material (e.g. changing uniforms)

I.e. I could access `aShaderPass.material`. In the new version of processing (5.6.0) I could access it using version 4.5.0.

The use case I have is that I need to change material uniforms at runtime when scroll position changes.

**Comment by vanruesc** [comment]
Hi,

the `material` accessor was replaced by the method [getFullscreenMaterial](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/Pass.js~Pass.html#instance-method-getFullscreenMaterial) in version 5. You can read more about this change in the release notes of [4.8.0](https://github.com/vanruesc/postprocessing/releases/tag/v4.8.0) and [5.0.0](https://github.com/vanruesc/postprocessing/releases/tag/v5.0.0). 

So instead of doing

```js
const uniforms = myShaderPass.material.uniforms;
```

you do

```js
const uniforms = myShaderPass.getFullscreenMaterial().uniforms;
```

**Comment by KholofeloMoyaba** [comment]
Thanks @vanruesc. I've also found that ```js
const uniforms = myShaderPass.quad.material.uniforms;
```
Also works.

**Comment by vanruesc** [comment]
Please note that `Pass.quad` is a private field which means that it may change without warning in future releases.
