### ISSUE TITLE
OulineEffect doesn't work on A-Frame

### ISSUE THREAD

**Issue by huhsame** [vanruesc/postprocessing#134]
Hello, 
I gave it a try to apply outline effect using your [A-Frame example.](https://jsfiddle.net/awrof47v/)

```
const outlineEffect = new PP.OutlineEffect(scene, camera, {
    blendFunction: 16,
    edgeStrength: 5,
    pulseSpeed: 0.0,
    resolution: 0.05,
    visibleEdgeColor: 0xffffff,
    hiddenEdgeColor: 0x22090a,
    blur: false,
    xRay: true,
    opacity: 1
});

smaaEffect.colorEdgesMaterial.setEdgeDetectionThreshold(0.05);
noiseEffect.blendMode.opacity.value = 0.6;
sepiaEffect.blendMode.opacity.value = 0.3;

let here = document.querySelector('#here').object3D
outlineEffect.setSelection(here.children);

const renderPass = new PP.RenderPass(scene, camera);
const effectPass = new PP.EffectPass(camera, outlineEffect,
    smaaEffect,noiseEffect, sepiaEffect, vignetteEffect);

effectPass.renderToScreen = true;
composer.addPass(renderPass);
composer.addPass(effectPass);
```
The changed part is only this code.
After adding outlineEffect, it doesn't appear. 
Other effects still work.
![image](https://user-images.githubusercontent.com/9151382/60314033-22d76480-999c-11e9-9674-431fae7757a7.png)

In console, outlineEffect is registered.
![image](https://user-images.githubusercontent.com/9151382/60314176-aee98c00-999c-11e9-9c11-2a1bd322a343.png)

How could I make it work? 

Thank you.

**Comment by vanruesc** [comment]
Hi,

the effect is working as expected, it's just that the blend function you're using (screen) doesn't work well in bright scenes. You can achieve better results with the _alpha_ blend function: https://jsfiddle.net/9cntay46/

Also notice that I've moved the `OutlineEffect` into a seperate `EffectPass` so that the antialiasing can affect the generated outlines. The other effects (noise, sepia and vignette) have been moved together with the `SMAAEffect`. That way the `EffectPass` can make sure that those effects don't interfere with the antialiasing.

You can keep all effects in one `EffectPass` if you like, but then you'll see more jagged lines.

**Comment by huhsame** [comment]
Thank you for your kind reply :)
