### ISSUE TITLE
NormalPass smooth normals

### ISSUE THREAD

**Issue by the-mush** [vanruesc/postprocessing#146]
I try to implement the SSAOEffect as shown in the example, and it seems to work pretty good (at least a lot better than the default one included with three.js). Only problem I found is that the "shadows" seem to ignore the normals of the mesh and they are casted in a way that every polygon has hard edges. This is the scenario:

* Mesh is an object generated by the GLTFLoader (I assume it is a *somethingsomething***BufferGeometry**)
* Object has been generated with Blender, applied "smooth shading".
* Three.js and the GLTFLoader properly recognize the normals from the file (If I don't use the SSAOEffect, I can see the smooth normals on the shine of the mesh).
* The material is a pretty basic setup, only a plain color.

What I suppose is that the NormalPass is ignoring or somehow applying a hard-shading to the normals. Tried to find a way in the API to change this, but it's clearly way over me 🤷‍♂️😅

**Comment by vanruesc** [comment]
Hi,

the `NormalPass` uses the `MeshNormalMaterial` from `three` to render the normals of your scene. That material respects normal maps, displacement maps and bump maps. My guess is that your SSAO `scale`, `bias` or `radius` is not properly configured for your scene. Another possibility is that the depth values of your scene are too inaccurate due to suboptimal camera settings.

Try the following code and check if your scene normals look fine:

```js
import { DepthEffect, EffectPass, NormalPass } from "postprocessing";

const depthPass = new EffectPass(camera, new DepthEffect());
const normalPass = new NormalPass(scene, camera);

normalPass.renderToScreen = true;
depthPass.renderToScreen = true;

// Uncomment individually to draw normals or depth:
//composer.addPass(normalPass);
//composer.addPass(depthPass);
```

Take a look at the following images for comparison:

| Normals | Depth |
|-----------|--------|
| ![normals-example](https://user-images.githubusercontent.com/9214917/64523531-c928da00-d2fc-11e9-9316-cf3eb269d0c2.png) | ![depth-example](https://user-images.githubusercontent.com/9214917/64523539-cd54f780-d2fc-11e9-81d3-7bbc25ada254.png) |

**Comment by the-mush** [comment]
Yes indeed! After trying it, it is related to the `scale`, `bias` and `radius` misconfigured properties for my scene. Your tests showed me that both the depth and normal passes give smooth normals, so that's out of the question.

Thank you for the help, the plugin and the info, and sorry for the noob question!

**Comment by vanruesc** [comment]
Nice, glad I could help!
