### ISSUE TITLE
Objects from different scenes in different effectComposers are not z-culled properly if one of the composer uses an effectpass

### ISSUE THREAD

**Issue by Brulogaz** [vanruesc/postprocessing#148]
Using postprocessing@6.7.0 on Chrome 77.0.3865.90 (64-bit), Windows 10 (64-bit), NVIDIA GTX 1080

I need to apply a SSAOEffect only on a few Objects so I created a second scene and a second effect composer. I started without the effect pass to make sure adding a second scene wouldn't cause any issue and it didn't. Everything rendered fine. Next step the normal pass, again works just fine. Finally I started having issue by adding the effect pass, the effect render as you would expect but it causes object from my second scene to render on top of everything. Effectively mimicking the behavior of calling clearDepth() in between my render calls. This happen no matter what effect I add to the pass so it's likely not caused by the SSAO effect but by the pass itself. 

I added a bunch of clearDepth = false to my pass and autoClearDepth false to my renderers but my guess is that there is some technical limitation in there wiping the depth information after an effect pass. Any tips would be greatly appreciated.

**Comment by vanruesc** [comment]
Hi!

> I need to apply a SSAOEffect only on a few Objects

The `SSAOEffect` relies on scene normals and depth. The user provides the normals by using a `NormalPass` and the effect automatically requests a depth texture from the `EffectComposer` which contains the depth of the entire scene. SSAO can be limited to a subset of objects by providing a custom depth texture and only rendering normals and depth of specific objects.

Here is a full example: https://codesandbox.io/s/postprocessing-ssao-xsokq

In that example, I use a custom `SSAOPrePass` to render the [normals](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/NormalPass.js~NormalPass.html) and [depth](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/DepthPass.js~DepthPass.html) of a [Selection](https://vanruesc.github.io/postprocessing/public/docs/class/src/core/Selection.js~Selection.html) of objects.

The `EffectPass` provides a `setDepthTexture` method to register a custom depth texture and depth packing format. You'll also need to set `needsDepthTexture` to `false` to prevent the `EffectComposer` from overwriting the depth texture.

```js
effectPass.setDepthTexture(ssaoPrePass.depth, RGBADepthPacking);
effectPass.needsDepthTexture = false;
```

> so I created a second scene and a second effect composer

With multiple scenes you'll run into problems since you can't easily share lights between scenes and shadows won't work properly. The `Selection` uses render layers to avoid these issues. I also don't recommend using multiple `EffectComposer` instances.

Keep in mind, that SSAO is a subtle effect that adds shadows to corners and crevices to improve the overall realism of a scene. If you hide a floor or a wall, the shadows of other objects that are close to it will look wrong and some shadows will be visible through other objects because they won't be properly occluded. Try looking at the Cornell Box in the given example from below.

**Comment by Brulogaz** [comment]
Thanks for the prompt answer! 

To be more precise I am trying to filter out billboard sprites, my second scene not being affected by the main scene's lighting wouldn't be an issue for me, it would even be ideal. I really wish I could make it works with two different scenes so I wouldn't need to reference every mesh in the selection pass. My terrain is destructible and built by a voxel engine so this really does sound like a lot of extra works to filter out a few predefined sprites.  Still you gave me a lot of information to work with so I will try messing around with the depth texture.

**Comment by vanruesc** [comment]
> I managed to get the desired result by adding a depth pass and setting its renderToScreen property to true.

Huh, that's weird. You can create composite results by letting two passes render to screen, but if the last pass is a fullscreen pass, it will overwrite the output of the first one. Your depth pass should have no effect at all since it doesn't even cause an internal buffer swap.

Without knowing your effect chain, I can only leave it at that. If you run into other problems feel free to re-open or create a new issue.
