### ISSUE TITLE
Inheriting from ThreeJS passes

### ISSUE THREAD

**Issue by twmmason** [vanruesc/postprocessing#179]
Hey, very nice library thanks for your work. Is there a way to inherit and use the passes that are built into the examples of ThreeJS - so for instance the UnrealBloomPass - I'm looking for a way to integrate it with your library? Thanks, T

**Comment by vanruesc** [comment]
This library is incompatible with the post processing examples from `three` due to API differences.
However, it's still possible to use the UnrealBloomPass mostly as-is.

See [this comment](https://github.com/vanruesc/postprocessing/issues/103#issuecomment-447338268) for details. Updated example: https://jsfiddle.net/mabx57q1/

Note that `UnrealBloomPass` imports a bunch of other files behind the scenes: https://cdn.jsdelivr.net/npm/three@0.114.x/examples/jsm/postprocessing/UnrealBloomPass.js

**Comment by twmmason** [comment]
Nice one thanks - this was the key bit:

`
UnrealBloomPass.prototype = Object.assign(UnrealBloomPass.prototype, {

	initialize() {},
	originalRender: UnrealBloomPass.prototype.render,

	render(renderer, inputBuffer, outputBuffer, delta, maskActive) {

		this.originalRender(renderer, outputBuffer, inputBuffer, delta, maskActive);

	}

});`

This makes it possible to chain three passes with yours - perfect!

Thanks again.
