### ISSUE TITLE
Replace RealisticBokehEffect with DepthOfFieldEffect

### ISSUE THREAD

**Issue by weiserhei** [vanruesc/postprocessing#198]
Hello,
Im replaceing the deprecated `RealisticBokehEffect` in my Project with the new `DepthOfFieldEffect` but it doesnt have all the options. To get the `fringe` I added the `ChromaticAberrationEffect`.
How to deal with the luminance options? Could you give me a hint on how to update whle keeping the looks? 

RealisticBokehEffect with `luminanceGain: 2, luminanceThreshold: 0.2`
![grafik](https://user-images.githubusercontent.com/7581732/80817221-5513ad00-8bd1-11ea-90bd-1b4ee5be9fad.png)

DepthOfFieldEffect + ChromaticAberrationEffect
![grafik](https://user-images.githubusercontent.com/7581732/80817153-2ac1ef80-8bd1-11ea-86c0-ce5b79a81458.png)

**Comment by vanruesc** [comment]
Hi!

> it doesnt have all the options.

These features didn't make it into the new `DepthOfFieldEffect` because the main goal was to get the blurring right. I'm a bit hesitant to add more features to this effect because it's already pretty complex. But it might be worth revisiting color fringing and luminance gain at some point.

> To get the fringe I added the ChromaticAberrationEffect.

The `ChromaticAberrationEffect` does basically the same as the fringe feature, but it isn't depth-aware and applies to the entire scene. Do you change the `focusDistance` of your DoF effect often or do you keep it at a fixed setting? If you change it dynamically you may have to adjust chromatic aberration as well.

I think it would be cool if we could feed some data from the `DepthOfFieldEffect` into the `ChromaticAberrationEffect` to modulate color fringing. But that requires some work.

> How to deal with the luminance options?

You could try to increase the diffuse or emissive color of bright objects to make them bloom more. Again, this won't be the same as depth-aware luminance gain, but it could be a viable solution. If that's not an option, you might have to stick to the `RealisticBokehEffect` for now.

**Comment by weiserhei** [comment]
Thank you for your explanation, I will try to recreate the effect using multiple other effects. What Im doing is just a demo but Ive been digging the details in this particular look 😎
