### ISSUE TITLE
EffectComposer autoRenderToScreen is undocumented

### ISSUE THREAD

**Issue by TyLindberg** [vanruesc/postprocessing#201]
When upgrading from a previous version, I noticed that the new automatic render-to-screen mechanism broke old code that expected the final result to be output to a framebuffer. This was fixed easily enough by setting `autoRenderToScreen` to false on the EffectComposer, but this variable doesn't seem to be documented.

Is this variable meant to be public or should it be internal to only the EffectComposer?

**Comment by vanruesc** [comment]
Hi,

the automatic render to screen mechanism was added to make the most common case where the last pass renders to screen more convenient. This behaviour disables itself if any given pass already has `renderToScreen` set to `true`. Since this came back to bite you, I'm assuming that none of your passes render to screen.

> Is this variable meant to be public or should it be internal to only the EffectComposer?

The `autoRenderToScreen` is supposed to be private. To be on the safe side, you should instead set the `renderToScreen` flag of your last pass to `false` right after adding it to the composer.

**Comment by TyLindberg** [comment]
Yup, you're correct. None of our passes rendered to the screen.

Setting `renderToScreen` to false after adding the last pass to the composer did the job. Previously I had tried setting `renderToScreen` to false before adding it to the composer, but I'm assuming the composer overrides that value after the pass is added.

Would it make sense to add a note about this in docs for users not wanting the final pass to render to screen?

**Comment by vanruesc** [comment]
> Would it make sense to add a note about this in docs for users not wanting the final pass to render to screen?

Maybe we should just make `autoRenderToScreen` public. This might actually result in a more natural API for this use case. What do you think?

**Comment by TyLindberg** [comment]
Yeah, that makes sense to me. Having it as a public variable that defaults to true seems like a solid solution for most use cases.

**Comment by vanruesc** [comment]
Alright, thanks for the feedback!

I've changed the visibility of the `autoRenderToScreen ` flag to public and added a note to the respective [wiki page](https://github.com/vanruesc/postprocessing/wiki/Rendering-to-Screen). The documentation will be updated with the next release.

**Comment by TyLindberg** [comment]
Great!
