### ISSUE TITLE
SSAO is not working as expected on v6.14.0

### ISSUE THREAD

**Issue by Ben-Mack** [vanruesc/postprocessing#207]
After upgrading to 6.14.0, the SSAO effect became really noisy with a strange look (it's like the normalPass is not correctly passed into SSAOEffect?)

Previously working result:
![image](https://user-images.githubusercontent.com/6309393/84876686-b0322e00-b0b1-11ea-99a2-ce34159494e0.png)

v6.14.0:
![image](https://user-images.githubusercontent.com/6309393/84876761-c9d37580-b0b1-11ea-825f-acdf7fab88c7.png)

I'm aware of radius property has changed its range to 0-1 and there's newly DepthDownsamplingPass. I've tried to implementing new code from SSAODemo and tinkering around params but no luck.

I was trying to reproduce in Codesandbox but then another error arised, please take a look: https://codesandbox.io/s/peaceful-star-3byox-614-u865x

![image](https://user-images.githubusercontent.com/6309393/84875101-b8896980-b0af-11ea-9c05-229a17dea279.png)

**Comment by vanruesc** [comment]
Thanks for the report. There seem to be several issues that cause the `SSAOEffect` to fail in WebGL 1. Looks like I haven't tested the effect enough and underestimated the impact of some of the changes I made.

The first issue is that the new `NoiseTexture` uses the `RedFormat` by default. I relied on [three's documentation](https://threejs.org/docs/#api/en/constants/Textures) and assumed this format was available in WebGL 1, but it actually isn't. This causes an "invalid internalformat" warning and the texture becomes unusable.

The other issue is that WebGL 1 hates arrays. Unfortunately, the `DepthDownsamplingPass` makes heavy use of arrays, which causes lots of console errors. I tried to change the array instantiations and even considered switching to matrices, but the shader relies on dynamic array indexing which is also not supported in WebGL 1. So the only solution here is to change the usage requirements for this pass to WebGL 2. Since the pass is broken in WebGL 1 anyway, I don't consider this a breaking change.

I'll publish a new version in a bit.

**Comment by vanruesc** [comment]
The issues have been fixed in `postprocessing@6.14.1`.

Please note that the `SSAOEffect` scales the sampling radius based on how far away the pixels are from the camera. The Cornell box is larger than one might think; it's actually as big as the Sponza scene. This causes more artifacts to appear on the large flat surfaces and distant AO appears much smaller. The artifacts can be suppressed by raising the bias factor, but there is a limit on how large far-away shadows can be in this scene.

I think it would be useful to have a setting that disables distances-based radius scaling.

**Comment by vanruesc** [comment]
It would be great if you could try out the new version in your scene to check if it fixes your problem.

**Comment by Ben-Mack** [comment]
Thank you for fixing it that quick!

> I think it would be useful to have a setting that disables distances-based radius scaling.

Yes, more flexible is better IMO

The new SSAO is much more noisier than v6.13.5, especially when you decrease preview window height, the smaller window height, the noisier it becomes.

v6.13.5: https://codesandbox.io/s/good-old-6135-p65ox
v6.14.1:  https://codesandbox.io/s/noisy-6141-bstg3

**Comment by Ben-Mack** [comment]
I tried using newest version with my scene. It still has the same problem as the screenshots I posted (noisy, doesn't look like AO at all).

**Comment by vanruesc** [comment]
Thanks for testing. The smaller sampling radii result in more false positives due to depth discontinuities, resulting in a noisy look. I added an option to disable distance-based radius scaling in `postprocessing@6.14.2`. Then I tried scaling the radius based on  linear depth and tied it to the effect render distance which had a positive impact on the noisy artifacts. I included these changes in `postprocessing@6.14.3`.

Please check if the new distance scaling works better in your scene. If it doesn't try disabling `distanceScaling`.

**Comment by Ben-Mack** [comment]
Thank you! It's no longer noisy now. The `distanceScaling` option has no effect to my scene.

One thing I noticed is from v6.14, changing camera's near can affects AO result quite a lot.

After upgrading to 6.14, I had to fine tune my camera's near just to get close to the result I had in v6.13. 
Changing distance/range threshold/falloff doesn't affect AO as much as the camera near did.
Also changing camera near in v6.13.5 doesn't affect AO the way it did in v6.14.

IMO it shouldn't behave like that, took me quite some time to figure it out.

**Comment by vanruesc** [comment]
> Thank you! It's no longer noisy now.

Nice, thanks for checking.

> One thing I noticed is from v6.14, changing camera's near can affects AO result quite a lot.

I'm unable to confirm this. The following screenshots show SSAO with depth-aware upsampling, most representative normal/depth downsampling, 32 samples per pixel, rendered at half resolution, intensity at `4`, bias at `0.025` and distance scaling with a minimum radius scale of `0.33`.

| Near 0.1, Far 1000 | Near 1.0, Far 1000 |
|-|-|
| ![point-one](https://user-images.githubusercontent.com/9214917/85201094-f4653e80-b2fc-11ea-9eaa-c66823115e09.jpg) | ![one](https://user-images.githubusercontent.com/9214917/85201096-fa5b1f80-b2fc-11ea-9d68-00c26e75cd45.jpg) |

There is a small difference between a near plane value of `0.1` and `1.0` but that's to be expected since the depth precision is much better when near is at `1.0`.

The distance threshold/falloff and range threshold/falloff settings make a big difference but adjusting them is a bit tricky right now. The unit of theses values will be changed to world space units in the next major version to make the configuration more intuitive.
