### ISSUE TITLE
SSAO color (or GTAO?)

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#211]
this is what it should look like

![Screenshot 2020-06-21 at 09 24 48 copy](https://user-images.githubusercontent.com/2223602/85219110-2cbe5880-b3a1-11ea-8554-bd5d25e2c8b6.jpg)

with postprocessing: https://codesandbox.io/s/ball-pit-1-o5ir0

<img width="605" alt="Screenshot 2020-06-21 at 09 28 13" src="https://user-images.githubusercontent.com/2223602/85219148-90488600-b3a1-11ea-824e-cc5a09638ea0.png">

i know this isn't ground thuth AO but could we still set the AO color somehow? in this case i would like to make it red for instance.

**Comment by vanruesc** [comment]
> could we still set the AO color somehow?

Yes, that should be possible. I'll look into it when I get a chance.

**Comment by vanruesc** [comment]
Added support for colorized ambient occlusion in `postprocessing@6.16.0`.

**Comment by vanruesc** [comment]
Sandbox for reference: https://codesandbox.io/s/ball-pit-1-vlhu6

**Comment by drcmda** [comment]
thanks, it looks awesome! the sandbox you posted had a halo for some reason, but i updated mine and it's exactly the effect i looked for https://codesandbox.io/s/ball-pit-1-mvkqs?file=/src/App.js

**Comment by drcmda** [comment]
@vanruesc from this question by @edankwan : https://twitter.com/edankwan/status/1280407226411290625 would that be possible, too? to deal out individual colors for objects?

**Comment by vanruesc** [comment]
I don't know if that can be done with the current scalable ambient obscurance algorithm. I'll try adding light bounce based on @gkjohnson's [GTAO implementation](https://github.com/vanruesc/postprocessing/issues/192#issuecomment-636593555) when I find some time.

**Comment by vanruesc** [comment]
Opened a new issue for the light bounce feature: #214.

**Comment by gkjohnson** [comment]
@vanruesc @drcmda just note that without actual surface information (diffuse color, roughness, metalness) of the objects before shadows are applied bounce light won't really be able to "reveal" any real information in shadowed areas. When I was working on it I found that it wound up muddying an image in more complex cases because of this but in simple cases it didn't look too bad. Perhaps one day we'll have deferred rendering and we'll have more information for these effects. I think it would be a good option, though!

The new AO color looks great, too.

**Comment by vanruesc** [comment]
@gkjohnson Thanks for the heads-up 👍
