### ISSUE TITLE
getter/setters + constructor args

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#217]
we released a first version of react-postprocessing: https://github.com/react-spring/react-postprocessing  and immediately bumped into this problem: https://github.com/react-spring/react-postprocessing/issues/8

there seems to be a difference between the constructor args and the internal values that drive the effect. as an example, we want to fade bloom, [the pp docs](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/BloomEffect.js~BloomEffect.html) state that the prop is called `luminanceThreshold`. but when the effect is created, `effect.luminanceThreshold` does nothing, instead it's being forwarded internally to `effect.luminanceMaterial.threshold` which is unfortunate.

it certainly works, see: https://codesandbox.io/s/r3f-basic-demo-zvu4g?file=/src/App.js

but that either forces users to browse source files, or us to abstract it - at the risk of pp changing stuff in any patch version.

the question is: would it possible to add setter/getters for config props that write into the correct uniforms and such automatically? that is what most threejs classes do, materials for instance. that would be such a welcome feature as it would make effects dynamic.

**Comment by vanruesc** [comment]
I wouldn't say that constructor parameters imply properties on the object. `BloomEffect.luminanceMaterial` is part of the public API which is described by the documentation. Changes to existing parts of the public API warrant a major version bump.

I guess this is a react-specific issue; normally it wouldn't be a problem to use `bloomEffect.luminanceMaterial.threshold` instead of `bloomEffect.luminanceThreshold`. Adding convenient abstraction on your end is not bad practice if it helps your use case.

> would it possible to add setter/getters for config props that write into the correct uniforms and such automatically? that is what most threejs classes do, materials for instance. that would be such a welcome feature as it would make effects dynamic.

I'd say that this is already how it is. However, the accessors are located [close to where the data is being kept](https://github.com/vanruesc/postprocessing/blob/0dc459d17a9bbbff019af4d522aea9b9b956792d/src/materials/LuminanceMaterial.js#L67-L89). Some settings are specific to materials and effects shouldn't always add layers on top of that. Note that I'm also trying to [reduce existing bloat](https://github.com/vanruesc/postprocessing/blob/0dc459d17a9bbbff019af4d522aea9b9b956792d/src/effects/BloomEffect.js#L163-L187).

Unfortunately, `three` isn't actually making much use of getters/setters. It's [frequently synchronizing uniforms](https://github.com/mrdoob/three.js/blob/301c953530285d97294a992ca5388ed3d8bc714a/src/renderers/WebGLRenderer.js#L1694) with properties on materials. See https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLMaterials.js for details.

**Comment by drcmda** [comment]
it's certainly possible to set props like that, users can set em like so:

```jsx
<Bloom luminanceMaterial-threshold={0.1} />
```

or imperatively via a reference, like in that demo.

it's just that it stretches the learning effort a bit, whereas if we could stick to the config parameters and the same names, that would cover most of the usecases i guess. it's like, if i want to learn bloom i have to know that i can set the treshholt via luminisanceThreshold, but then if i want to change it later on, it's something else, different name even. so im constantly browsing through doc files.

if internals don't change we can also abstract it like that in the wrapper.

**Comment by drcmda** [comment]
i think we're going to extend PP classes with setter/getters that match the config args as well as imperative function args (setEdgeThreshold, etc). that seems like not so much trouble on our side and it'll be easier to type. thanks for your time!
