### ISSUE TITLE
Transparent Canvas ?

### ISSUE THREAD

**Issue by stephanedemotte** [vanruesc/postprocessing#226]
Hello.

Can we set a transparent background in the composer.

i've got 

```
  const renderer = new WebGLRenderer({ 
    powerPreference: "high-performance",
    stencil: false,
    depth: false,
    canvas: canvas.value,
    alpha: true,
    antialias: true
  })
```

When i use 

```
  const render = () => {
    renderer.render(scene, camera)
  } 
```

But i've got a black background when i render 
```
  const render = () => {
    composer.render(clock.getDelta())
  } 
```

Any idea ?

Thank you !

**Comment by MrMateo7** [comment]
Hi!
How do you solve this?

**Comment by vanruesc** [comment]
@anat Thanks for the report; it looks like the internal mask pass of the `DepthOfFieldEffect` isn't being configured properly when a transparent canvas is used. I'll include a fix in the next release. You can use the following hack to make it work now:

```js
import { MaskFunction } from "postprocessing";

const maskMaterial = depthOfFieldEffect.maskPass.getFullscreenMaterial();
maskMaterial.maskFunction = MaskFunction.MULTIPLY;
```

Please note that it's not advisable to comment on old issues due to greatly reduced visibility. It's generally better to open a new ticket or discussion. You can reference related issues by their number, e.g. #226.

**Comment by anat** [comment]
@vanruesc Thanks a lot for your answer !

It work as expected and it looks great.

Your package is really great, by the time I was using spite/Wagner and it was really nice. Thank you for providing us your awesome work.

I will remember your advice ;) (#issue)
