### ISSUE TITLE
Custom Effect Fragment Shader Help

### ISSUE THREAD

**Issue by austinmayer** [vanruesc/postprocessing#243]
I have successfully created a Custom Effect via `react-postprocessing` based on a lightweight fullscreen effect from https://www.airtightinteractive.com/demos/js/badtvshader/. My effect works, I'm seeing it influence the scene but I'm not confident in my shader re-writes and am looking for a bit more detail on how vUv vs. uv and texture / inputBuffer translate from more "stock" fragment shaders from THREE.

The effect works but there is a static part of the original scene that remains persistent and my custom effects aren't chaining effectively.

Any help would be much appreciated.

https://codesandbox.io/s/r3f-postprocessing-customeffect-rd-4w43o?file=/shaders/HorizontalBlurShader.js

**Comment by vanruesc** [comment]
Hi,

I can't help with the React part, but you'd implement these effects like this using the vanilla library:
https://codesandbox.io/s/frosty-bush-jbx64?file=/src/App.js

#### Implementation details
- Effects should always use the `uv` parameter that is provided to `mainSupport`, `mainUv` or `mainImage`. Don't use `vUv`.
- The `HorizontalBlurEffect` samples the `inputBuffer` in its fragment shader and is therefore a convolution effect.
  - Such effects should specify the [EffectAttribute](https://vanruesc.github.io/postprocessing/public/docs/variable/index.html#static-variable-EffectAttribute) `CONVOLUTION`.
- The `BadTVEffect` only manipulates the UV coordinates, so the `mainUv(const inout uv)` function should be used.
  - Effects that modify UVs in the fragment shader can't be merged with convolution effects. Otherwise, the original image will bleed through.

Check the [Wiki](https://github.com/vanruesc/postprocessing/wiki/Custom-Effects) for more details.

**Comment by vanruesc** [comment]
I forgot to say that the original `HorizontalBlurShader` used a `texture` uniform to bind the input image. Since effects already have access to this texture via the central `inputBuffer` sampler, you don't need it.

**Comment by austinmayer** [comment]
Thanks for the help, this is exactly what I was looking for clarity on. Appreciate it!
