### ISSUE TITLE
Wiki: Specify which passes require the override material workaround

### ISSUE THREAD

**Issue by marcofugaro** [vanruesc/postprocessing#247]
### Is your feature request related to a problem?

While reading [the wiki about `OverrideMaterialManager.workaroundEnabled`](https://github.com/vanruesc/postprocessing/wiki/Skinned-and-Instanced-Meshes), it says:

> Some passes and effects use override materials to render special data such as view space normals.

However I don't know which specific passes use overrideMaterial and I don't know if I need to check for this issue or I just don't need to care with the passes I'm using in my project.

### Describe the solution you'd like

Add a list of passes which use the overrideMaterial internally.

The wiki is really useful btw, it explains a lot of things.

**Comment by vanruesc** [comment]
It's not necessary to know which effects use override materials.

Three's override mechanism can't handle scenes that contain a mix of skinned and static meshes. If you don't enable the workaround, effects that use override materials will fail. If you don't use effects that use override materials, the workaround won't have any impact on performance. The workaround is limited to passes and effects - it doesn't affect the common override material mechanism in any way.

I recommend enabling the workaround at all times. It's disabled by default because people should be aware of the possible performance issues before enabling it. The workaround will eventually become obsolete when MRT and NodeMaterials land in `three`.

To fully answer your question, the workaround currently affects the following effects and passes:
- `OutlineEffect`
- `SSAOEffect`
- `SelectiveBloomEffect`
- `DepthPass`
- `NormalPass`

Technically, the `GodRaysEffect` is also affected, but there is no impact on performance.

**Comment by vanruesc** [comment]
I've added the information above to the wiki page.
