### ISSUE TITLE
Expensive demos run ~20fps on a Macbook Pro

### ISSUE THREAD

**Issue by marcofugaro** [vanruesc/postprocessing#259]
### Description of the bug

The most expensive demos (antialiasing, color-depth, color-grading, depth-of-field, glitch, god-rays, pattern, pixelation, shock-wave, ssao, texture, performance) run at about 20fps on a 2018 Macbook Pro (any browser).

This is due to this line here:
https://github.com/vanruesc/postprocessing/blob/71cffb8ebd7046c097bd096ad8addf5ee8599ab5/demo/src/index.js#L95

The pixelRatio is by default 2 on the mac. In most production applications, the renderer pixelRatio is clamped to 1.5, or even set to 1 if any postprocessing is used.

You should remove that line in my opinion, even if it results in a little bit of resolution loss on mac devices.

| Current | PixelRatio set to 1 |
|------|------------|
|<img width="1056" alt="Screenshot 2021-01-24 at 00 38 37" src="https://user-images.githubusercontent.com/7217420/105617620-e79f5080-5ddf-11eb-9905-d79880a2f2f0.png">|<img width="1055" alt="Screenshot 2021-01-24 at 00 39 10" src="https://user-images.githubusercontent.com/7217420/105617624-f38b1280-5ddf-11eb-9c84-5bec36b605c6.png">|

### Hardware

<img src="https://user-images.githubusercontent.com/7217420/105617436-95a9fb00-5dde-11eb-9695-41d44c804231.png" width="400" />

**Comment by vanruesc** [comment]
Rendering at half resolution definitely improves pixel throughput, especially with post processing effects. But wouldn't you normally choose native resolution over post processing effects when the hardware struggles to keep up?

**Comment by marcofugaro** [comment]
@vanruesc it depends on the project, sometimes the postprocessing effects are fundamental, sometimes they're the cherry on top.

But for the demos, I'd personally make them run decently on current hardware, this kind of macbook is what most developers have, it's not even that old.

**Comment by marcofugaro** [comment]
Maybe set the max pixelRatio to 1.5? With that you get ~30-40fps on my machine. The image quality difference is barely noticeable.

**Comment by vanruesc** [comment]
I'm opposed to limiting the pixel ratio because it would prompt other people to ask me later why the demo looks so blurry.

My phone has a pixel ratio of 3 and results would look bad with a ratio of 1.5. I understand the pragmatic motivation behind this, but trading quality for performance is something users should do in their apps. [Three's](https://github.com/mrdoob/three.js/blob/ff5573cb0a6286bf1d7e38cbdace0e1a045cf5f6/examples/webgl_postprocessing_dof.html#L57) [examples](https://github.com/mrdoob/three.js/blob/ff5573cb0a6286bf1d7e38cbdace0e1a045cf5f6/examples/webgl_postprocessing_godrays.html#L88) [also](https://github.com/mrdoob/three.js/blob/ff5573cb0a6286bf1d7e38cbdace0e1a045cf5f6/examples/webgl_postprocessing.html#L31) [use](https://github.com/mrdoob/three.js/blob/ff5573cb0a6286bf1d7e38cbdace0e1a045cf5f6/examples/webgl_performance.html#L79) [window.devicePixelratio](https://github.com/mrdoob/three.js/blob/ff5573cb0a6286bf1d7e38cbdace0e1a045cf5f6/examples/webgl_morphtargets.html#L58) and [this Khronos article](https://www.khronos.org/webgl/wiki/HandlingHighDPI) recommends the use of `window.devicePixelRatio` to avoid undesired aliasing.

**Comment by marcofugaro** [comment]
Alright, thanks for the explanation.
