### ISSUE TITLE
Using renderer.readRenderTargetPixels() inside a custom Pass 

### ISSUE THREAD

**Issue by juliangarnier** [vanruesc/postprocessing#263]
Hi,

I'm trying to use `renderer.readRenderTargetPixels()` inside the `render()` function of a custom Pass to perform GPU Picking in order to update the FullscreenMaterial fragment shader with the picked values.
Since all the materials in my scene are rendered using basic vertex colors, there is no need to render the scene twice to get a separated WebGLRenderTarget to store the vertex colors values for picking.

[The documentation mentions](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/Pass.js~Pass.html#instance-method-render) that the `render()` function second parameter is the inputBuffer from the previous pass (In my case the previous pass is a RenderPass).

Since inputBuffer is a `WebGLRenderTarget`, I was expecting to be able to perform `renderer.readRenderTargetPixels(inputBuffer, x, y, 1, 1, readPixel)` inside the render function, but the returned pixels are always black.
Passing `inputBuffer.texture` and the coordinates to the shader uniforms works as expected, so I don't think the problem is related to this part.

And the GPU picking code works when I use a traditional setup by rendering the scene twice like so 
```
const pickingTexture = new WebGLRenderTarget(doc.width, doc.height, {
  minFilter: LinearFilter, 
  magFilter: NearestFilter,
  format: RGBAFormat,
  type: FloatType
});
```
with in the render code:
```
renderer.setRenderTarget(pickingTexture);
renderer.render(scene, camera);
renderer.setRenderTarget(null);
```
But this method requires to render the scene twice.

I'm confused, why does `inputBuffer` returns only black values when used in `renderer.readRenderTargetPixels` but not when passed to the shader?
Is it even possible to call `renderer.readRenderTargetPixels` in the `render()` function?

Here is the render function of my custom Pass for context: 

```
render(renderer, inputBuffer, outputBuffer, deltaTime, stencilTest) {

  const material = this.getFullscreenMaterial();

  material.uniforms.tDiffuse.value = inputBuffer.texture; // The shader reads the pixel from the previous pass perfectly

  const readPixel = new Float32Array(4);
  const x = Math.floor((material.uniforms.position.value.x + 1) * (width / 2));
  const y = Math.floor((material.uniforms.position.value.y + 1) * (height / 2));
  renderer.readRenderTargetPixels(inputBuffer, x, y, 1, 1, readPixel);

  console.log(readPixel); // Returns only [0., 0., 0., 0.]

  renderer.setRenderTarget(this.renderToScreen ? null : outputBuffer);
  renderer.render(this.scene, this.camera);

}
```

Any input is appreciated, thanks!

**Comment by vanruesc** [comment]
> Is it even possible to call renderer.readRenderTargetPixels in the render() function?

Yes, that should work, granted the type of the input buffer is `HalfFloatType` or `FloatType`. How are you initializing your composer? A complete code example would be useful to track down the issue.

**Comment by juliangarnier** [comment]
> that should work if the type of the input buffer is HalfFloatType or FloatType
That was my problem, I didn't change the frame buffer type of the composer!
I solved the problem with 
```
    const composer = new EffectComposer(renderer, {
      frameBufferType: FloatType
    });
```
Now `renderer.readRenderTargetPixels()` in the the pass render function works as expected.
Thank you for the quick reply, and bravo for the library, pleasant to use and really well designed.
Keep up the great work!

**Comment by unphased** [comment]
I'm trying to write a custom Pass to do something similar but different: I want to raycast the distance in order to control the camera, without doing octree shenanigans on the CPU. This means I just need to read a single pixel out of the depth buffer. Now if I wasn't using postprocessing I suppose I would need to hack react-three-fiber to get that done, but I am hoping that writing a self-contained special Pass for postprocessing and wiring it through would be an elegant way to go about it. 

I'm choosing not to make a new issue because I think a lot of the same principles apply. 

I also am learning that WebGL doesn't directly provide the ability to read depth buffer (or depth texture, it seems) values back to the CPU: only the main color buffer contents. So, it would appear that i really need to do a real actual custom render pass with a shader which samples from the previous renderbuffer's depth used as a texture and then read the output of that to work with it on the CPU. And the right way to do this is in code inside the `render` function for the new custom Pass?

**Comment by vanruesc** [comment]
@unphased You're on the right track. The best way to do this would probably be to copy depth from the depth texture into a render target which can then be read with `renderer.readRenderTargetPixels()`. So in this case you'd create a custom `ShaderMaterial` and a custom `Pass` that uses the material as a fullscreen material:

<details><summary>DepthCopyMaterial</summary>
<p>

```js
import { ShaderMaterial, Uniform } from "three";

const depthCopyVertexShader = `varying vec2 vUv;

void main() {

	vUv = position.xy * 0.5 + 0.5;
	gl_Position = vec4(position.xy, 1.0, 1.0);

}`;

const depthCopyFragmentShader = `#include <packing>

#if INPUT_DEPTH_PACKING == 3201

	uniform lowp sampler2D depthBuffer;

#else

	#ifdef GL_FRAGMENT_PRECISION_HIGH

		uniform highp sampler2D depthBuffer;

	#else

		uniform mediump sampler2D depthBuffer;

	#endif

#endif

varying vec2 vUv;

void main() {

	#if INPUT_DEPTH_PACKING == OUTPUT_DEPTH_PACKING

		gl_FragColor = texture2D(depthBuffer, vUv);

	#else

		#if INPUT_DEPTH_PACKING == 3201

			float depth = unpackRGBAToDepth(texture2D(depthBuffer, vUv));
			gl_FragColor = vec4(vec3(depth), 1.0);

		#else

			float depth = texture2D(depthBuffer, vUv).r;
			gl_FragColor = packDepthToRGBA(depth);

		#endif

	#endif

}`;

class DepthCopyMaterial extends ShaderMaterial {

	constructor() {

		super({

			type: "DepthCopyMaterial",

			defines: {
				INPUT_DEPTH_PACKING: "0",
				OUTPUT_DEPTH_PACKING: "0"
			},

			uniforms: {
				depthBuffer: new Uniform(null)
			},

			fragmentShader: depthCopyFragmentShader,
			vertexShader: depthCopyVertexShader,

			toneMapped: false,
			depthWrite: false,
			depthTest: false

		});

	}

	get inputDepthPacking() {

		return Number(this.defines.INPUT_DEPTH_PACKING);

	}

	set inputDepthPacking(value) {

		this.defines.INPUT_DEPTH_PACKING = value.toFixed(0);
		this.needsUpdate = true;

	}

	get outputDepthPacking() {

		return Number(this.defines.OUTPUT_DEPTH_PACKING);

	}

	set outputDepthPacking(value) {

		this.defines.OUTPUT_DEPTH_PACKING = value.toFixed(0);
		this.needsUpdate = true;

	}

}
```

</p>
</details>

<details><summary>DepthSavePass</summary>
<p>

```js
import {
	BasicDepthPacking,
	FloatType,
	NearestFilter,
	UnsignedByteType,
	WebGLRenderTarget
} from "three";

import { Pass } from "postprocessing";

class DepthSavePass extends Pass {

	constructor(depthPacking = BasicDepthPacking) {

		super("DepthSavePass");

		const material = new DepthCopyMaterial();
		material.outputDepthPacking = depthPacking;
		this.setFullscreenMaterial(material);
		this.needsDepthTexture = true;
		this.needsSwap = false;

		this.renderTarget = new WebGLRenderTarget(1, 1, {
			type: (depthPacking === BasicDepthPacking) ? FloatType : UnsignedByteType,
			minFilter: NearestFilter,
			magFilter: NearestFilter,
			stencilBuffer: false,
			depthBuffer: false
		});

		this.renderTarget.texture.name = "DepthSavePass.Target";

	}

	get texture() {

		return this.renderTarget.texture;

	}

	get depthPacking() {

		return this.getFullscreenMaterial().outputDepthPacking;

	}

	setDepthTexture(depthTexture, depthPacking = 0) {

		const material = this.getFullscreenMaterial();
		material.uniforms.depthBuffer.value = depthTexture;
		material.inputDepthPacking = depthPacking;

	}

	render(renderer, inputBuffer, outputBuffer, deltaTime, stencilTest) {

		renderer.setRenderTarget(this.renderToScreen ? null : this.renderTarget);
		renderer.render(this.scene, this.camera);

	}

	setSize(width, height) {

		this.renderTarget.setSize(width, height);

	}

}
```

</p>
</details>

Add this pass after your `RenderPass` and use `depthSavePass.renderTarget` for `renderer.readRenderTargetPixels()`, preferably in another, subsequent custom pass for better separation of concerns. Note that depth values won't be linear if you're using a perspective camera, so you'll have to convert that on the CPU to get correct distance readings. And if you use `RGBADepthPacking` to avoid the use of `FloatType`, you'll have to decode that on the CPU as well. Relevant conversion code: [perspective to linear](https://github.com/vanruesc/postprocessing/blob/db22dbc5f94b570e0a8162c80dfca9e7f245306a/src/materials/glsl/effect/shader.frag#L27-L53) and [conversion functions](https://github.com/mrdoob/three.js/blob/ef6a69160b795b7a03b676f6b9708d0a358736d4/src/renderers/shaders/ShaderChunk/packing.glsl.js#L38-L50).

Disclaimer: not fully tested.

**Comment by unphased** [comment]
Thank you so much @vanruesc for the assistance, you're the best!

Although it'd be more straightforward to use FloatType to store the depth value, if I am to understand this correctly, one of the fundamental design aspects of GL ES and by extension WebGL is that the implementation is allowed to limit the floating point precision of floating point buffer types? So even if I have the capabilities to use FloatType here, on many mobile devices I may end up receiving a poor float precision type and it would actually be limiting compared to the manual depth packing/unpacking approach, and so I perhaps should go with the latter to guarantee this accuracy?

If I don't need the depth for any location other than where the mouse is, would it be a sensible optimization (it should eliminate a lot of memory bandwidth consumption at least) to set a 1x1 rendertarget for use with that DepthCopyMaterial?

**Comment by unphased** [comment]
@vanruesc Just a quick followup question. I was looking at the blur demo implementation (it's the one I chose to copy and hack away at to prototype this new pass i'm writing) and I was confused about one thing: `menu.add(texturePass, "dithering");`

Mainly I guess it's visually impossible to discern whether this is enabled or not (and therefore whether the checkbox even does anything at all), but obviously dithering is a subtle effect and blur is never a source of banding, so that's unsurprising after all. 

I think, I'm not sure, since the dat.gui doc doesn't clarify, but the menu add call like that somehow is able to figure out that dithering on a EffectPass returns a boolean and thus provides a checkbox in the gui. Then I'm curious about why in the Bloom demo we have this code

    menu.add(passA, "dithering").onChange((value) => {
      passB.dithering = value;
    });

Why not `menu.add(passB)`?

**Comment by unphased** [comment]
Your provided code totally works!

![image](https://user-images.githubusercontent.com/1542910/107010227-0e587200-6764-11eb-9219-4e5d20464388.png)

What I have noticed so far:
- it does not look like what's shown changes whether I specify `BasicDepthPacking` or `RGBADepthPacking`, though this may be due to magic already handling the packing/unpacking
- there is a difference, though on my iPhone 12 Pro Max, the DepthSavePass renders nothing with `BasicDepthPacking` but works with `RGBADepthPacking` and looks just like desktop!

The last thing of note is that my A12X and A14 iOS devices run my hacked version of the blur demo at 60fps (or close to it in the case of the ipad) while my Intel Macbook from 2017, even with AMD dGPU struggles to reach 20fps. wow. Anyway this is very encouraging that it is all already working on all these devices. Between this and an implementation of GPU picking it will be possible to get full-featured WYSIWYG mouse raycasting!

**Comment by vanruesc** [comment]
> So even if I have the capabilities to use FloatType here, on many mobile devices I may end up receiving a poor float precision type

Well, you'd have to check on the device if [EXT_color_buffer_float](https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float) (WebGL 2) or [WEBGL_color_buffer_float](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_color_buffer_float) (WebGL 1) is supported. This guarantees 32 bit float buffers. The depth packing approach works in every context and without extensions, but it's a bit more complicated to use and requires additional calculations.

> would it be a sensible optimization (it should eliminate a lot of memory bandwidth consumption at least) to set a 1x1 rendertarget for use with that DepthCopyMaterial?

Sure, you can do that. You'll just need the texel size of the depth texture and the normalized mouse screen position to calculate the texture sampling coordinates.

> Mainly I guess it's visually impossible to discern whether this is enabled or not (and therefore whether the checkbox even does anything at all), but obviously dithering is a subtle effect and blur is never a source of banding, so that's unsurprising after all.

The [dithering](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/EffectPass.js~EffectPass.html#instance-get-dithering) flag enables banding removal which can occur with low blur resolutions and large blur kernels:

| No dithering | Dithering |
|-|-|
| ![no-dithering-2](https://user-images.githubusercontent.com/9214917/107048755-94f36a80-67c9-11eb-8837-47030df8c6ec.png) | ![dithering-2](https://user-images.githubusercontent.com/9214917/107048797-a0469600-67c9-11eb-9b38-ed93facf51ad.png) |

> I think, I'm not sure, since the dat.gui doc doesn't clarify, but the menu add call like that somehow is able to figure out that dithering on a EffectPass returns a boolean and thus provides a checkbox in the gui.

That's because it is, in fact, a boolean property on [EffectPass](https://github.com/vanruesc/postprocessing/blob/db22dbc5f94b570e0a8162c80dfca9e7f245306a/src/passes/EffectPass.js#L329-L360).

**Comment by unphased** [comment]
>  if EXT_color_buffer_float (WebGL 2) or WEBGL_color_buffer_float (WebGL 1) is supported.

[caniuse](https://caniuse.com/?search=color_buffer_float) shows no Safari flavor supports them, which is consistent with what I see. Safari's WebGL2 support is also totally incomplete AFAIK.

> dithering 

Thanks for the example! Wow, it's actually possible to see color banding at 8bpp... Learn something new every day. I appreciate your attention to detail. Does this dithering work with lower bit depth input, or is it only for dithering 8bpp output? I think it would be much easier to actually see its effect if it's applied in the color-depth demo!

> boolean property

How might I add a 2nd dithering checkbox for the dithering prop on a 2nd pass in a demo? Itll seemingly work but both checkboxes will have the same label.

**Comment by vanruesc** [comment]
> Does this dithering work with lower bit depth input, or is it only for dithering 8bpp output?

Interesting point; it seems that [dithering assumes a bit depth of 8](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/dithering_pars_fragment.glsl.js). I'll have to look into that to make sure it works with float and half float buffers. In other words, dithering with higher bit depths might be broken atm. The lowest possible bit depth is 8 bit.

> I think it would be much easier to actually see its effect if it's applied in the color-depth demo!

The `ColorDepthEffect` only simulates lower color depths. It still writes to float or uint8 buffers depending on the settings. I think there's a good chance that dithering won't really affect visuals in that demo.

> How might I add a 2nd dithering checkbox

You can create a plain object and use it as a proxy:

```js
const proxy = {
	"dithering A": effectPassA.dithering,
	"dithering B": effectPassB.dithering
};

menu.add(proxy, "dithering A").onChange(value => (effectPassA.dithering = value));
menu.add(proxy, "dithering B").onChange(value => (effectPassA.dithering = value));
```

**Comment by unphased** [comment]
Yeah I'm thinking it would indeed be cool to be able to simulate retro rendering techniques while leveraging GPUs for that. It would be a neat look to have 1, 2, 4, or 6 bpp rendered with dithering. 

Cheers! Thanks!

**Comment by unphased** [comment]
I was stuck conceptually for a little bit but I think I figured it out. The critical step in raycasting from the camera via depth buffer read is in taking that depth and converting the location of the pixel into NDC to get all 3 coordinates and unprojecting that with the camera, which three.js provides a method for. 

It certainly seems that `perspectiveDepthToViewZ` is doing the portion of this work that doesn't account for the X and Y values. it will produce the eye space Z coordinate, and this is fine as an approximation for distance from the camera, when near the center of the frustum, it doesn't actually capture the actual distance when off center!

**Comment by vanruesc** [comment]
Nice, thanks for the info!

Maybe we could add this as a `DepthPickingPass` to `postprocessing` at some point. PRs are welcome 😄

**Comment by unphased** [comment]
That's my plan. Unclear what the best architecture would be to wire it up to control the camera but I'll try to think of something reasonable.
