### ISSUE TITLE
OutlineEffect only show one side on a Double Side ShapeGeometry

### ISSUE THREAD

**Issue by lknstanley** [vanruesc/postprocessing#265]
### Description of the bug

`OutlineEffect` only apply one side to `ShapeGeometry` mesh even the material set the `side` to `DoubleSide`.

### To Reproduce

1. Create `Shape` and `ShapeGeometry`
2. Modify the material to use `DoubleSide` for `side`
3. Add shape mesh to scene
4. Initialise `EffectComposer` and `OutlineEffect`
5. Add shape mesh to `OutlineEffect` selection

[Link to demo](https://codesandbox.io/s/threejs-postprocessing-issue-cek3l?file=/src/App.js)

### Expected behavior

I can see the outline on both side.

### Screenshots

Frontside
![front](https://user-images.githubusercontent.com/11662246/106243772-dd98aa00-6244-11eb-929d-53ed19c8feaf.png)

Backside
![back](https://user-images.githubusercontent.com/11662246/106243757-db365000-6244-11eb-989b-f1d451fe2a71.png)

### Library versions used

 - Three: 0.124.x
 - Post Processing: 6.x.x

### Desktop

 - OS: Windows 10
 - Browser Chrome Version 87.0.4280.141
 - Graphics hardware: NVIDIA RTX 2060 SUPER

**Comment by vanruesc** [comment]
Thanks for reporting this.

The `OutlinePass` renders the depth of selected objects via three's override material system. Unfortunately,  this system completely ignores all values of the original materials. This library provides an [overide material workaround](https://github.com/vanruesc/postprocessing/wiki/Skinned-and-Instanced-Meshes) that fixes important issues with skinned and instanced meshes, but it doesn't add support for all individual material settings like `normalMap` and `side` because this would drastically increase the number of additional override materials.

However, I think that the `side` field doesn't really belong to the material because it affects how the geometry is rendered so I think it should be fine to support it. I'll publish a patch in a bit.

In any case, please make sure the override material workaround is enabled.

**Comment by vanruesc** [comment]
Added support for `BackSide` and `DoubleSide` to `OverideMaterialManager` in `postprocessing@6.20.2`.
