### ISSUE TITLE
Add "frame" uniform for custom effects

### ISSUE THREAD

**Issue by funwithtriangles** [vanruesc/postprocessing#269]
### Is your feature request related to a problem?

Using `time` for a shader isn't always what we want. For feedback effects, it's sometimes necessary to check if the first frame has passed before using a certain buffer as feedback.

### Describe the solution you'd like

Add `uniform int frame`. It's just a simple frame count of how many times the composer has rendered.

### Describe alternatives you've considered

It's simple to add this as a custom uniform to each of my effects, but is a bit cumbersome if I am doing this multiple times. I can also make use of the `time` uniform but this isn't always accurate, if there is some lag at the start of the application, etc.

### Notes

I'm happy to go ahead and do this myself with a PR, just worth checking if this feature is welcome or not!

**Comment by funwithtriangles** [comment]
Closing this, as in my case I've realised that I've got multiple effects starting at different times, so the built in `frame` uniform would only actually be useful for the first effect. I'd have to use custom uniforms anyway for all the others.

**Comment by funwithtriangles** [comment]
I initially closed this, as in my case I've realised that I've got multiple effects starting at different times, so the built in `frame` uniform would only actually be useful for the first effect.

However if this frame value was updated and kept separate inside each effect, then perhaps it would still be useful. Not sure if this is how things work internally though.

**Comment by vanruesc** [comment]
I want to avoid adding more default uniforms to the `EffectMaterial` because the minimum limit of supported uniforms is 16 according to the spec (see [GL_MAX_FRAGMENT_UNIFORM_VECTORS](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml)). The plan is to further reduce the amount of predefined uniforms in the next major release.

> However if this frame value was updated and kept separate inside each effect, then perhaps it would still be useful. Not sure if this is how things work internally though.

That would mean adding a default uniform to the `Effect` base class which would increase the total number of uniforms in the composite shader by one per effect. I don't see why we'd want to do that, though.

Wouldn't it be possible to render something into your feedback buffer in `Effect.initialize()` before rendering starts?

**Comment by funwithtriangles** [comment]
That all makes sense. I wasn't aware of `Effect.initalize()`, looks useful though, thanks!
