### ISSUE TITLE
autoRenderToScreen and disabled last pass

### ISSUE THREAD

**Issue by swingingtom** [vanruesc/postprocessing#271]
Hi, first, thanks for actively maintaining this library. 

## Motivations
 `EffectComposer.autoRenderToScreen` feature do not take `Pass.enabled` into account. Then if the last pass is disabled, the render output is empty.

## Option A : Internal handling 
The EffectComposer could check to find last enabled Pass, instead of currently rendering to screen the last Pass no matter what. 

### Pros 
- No brainer for user. No 'Why is this now empty ?'

### Cons 
- A bit more code/complexity not really "postprocessing" related in the library. 

## Option B : User responsibility

Users should handle their own stuff and adding a last disabled pass its on their side. 
Simply consider adding a Warning if the last Pass is disabled, in order to notice them.

**Comment by vanruesc** [comment]
I think this should be left up to the user for now because changing the `renderToScreen` flag at runtime triggers a shader recompilation if the output encoding is not `LinearEncoding`. So tying this to `Pass.enabled` would cause unexpected freezes in other use cases. The recompilation happens because `three` bakes output encoding functions into shaders based on the render target.
