### ISSUE TITLE
MultiRenderTarget samples not working with aframe 1.2.0 ( three 125.1) 

### ISSUE THREAD

**Issue by arpu** [vanruesc/postprocessing#282]
MultiRenderTarget samples not working with aframe 1.2.0 ( three 125.1) 

### To Reproduce

https://jsfiddle.net/9q1cky8m/5/

### Expected behavior

using multisamples

### Screenshots

![Bildschirmfoto von 2021-03-25 16-09-47](https://user-images.githubusercontent.com/14173/112495857-90d4d980-8d84-11eb-8922-601b7f2f8f6a.png)
.

### Library versions used

 - Three: [e.g. 0.125.1]
 - Post Processing: [6.21.2]

### Desktop

 - OS: [Linux]
 - Browser [e.g. Chrome 89.0]
 - Graphics hardware: [AMD RX 460 ]

### Mobile

 - OS: [e.g. Android 10]
 - Browser [e.g. Firefox 68.11.0]

**Comment by vanruesc** [comment]
I'm unable to reproduce this issue; the given example works fine on my system (Windows 10, NVIDIA GTX 1060, Chrome & Firefox).

Is the report you posted for the RX 460 or the iPhone 6? Please provide a screenshot of the issue and a log of the console output.

**Comment by arpu** [comment]
Hey,

yes it "works" but it looks like multisample is not used 
![Bildschirmfoto von 2021-03-25 18-49-08](https://user-images.githubusercontent.com/14173/112519645-dd2b1400-8d9a-11eb-95ed-63569899dbe7.png)

and https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk

spectorjs show samples: 0

**Comment by arpu** [comment]
ah and sorry this is on Desktop Linux with chrome 89  amd rx460

**Comment by vanruesc** [comment]
I meant that MSAA works on my machine (and my Android 9 phone):

| No Multisampling | Multisampling &times; 8 |
|-|-|
| ![no-msaa](https://user-images.githubusercontent.com/9214917/112524797-858fa700-8da0-11eb-8244-426c956c2d4f.jpg) | ![msaa](https://user-images.githubusercontent.com/9214917/112524842-8f190f00-8da0-11eb-9e4a-464a6568a22e.jpg) |

This might be a device and/or driver issue on your end. Do you use a CPU with integrated graphics? If so, then maybe your browser is incorrectly using that iGPU instead of your RX 460. Integrated graphics may not support WebGL 2 which is required for MSAA on offscreen frame buffers.

**Comment by vanruesc** [comment]
> spectorjs show samples: 0

I guess Spector.js only inspects the WebGL context. MSAA for postprocessing works by setting samples on an offscreen [WebGLMultisampleRenderTarget](https://threejs.org/docs/?q=WebGLMultisampleRenderTarget#api/en/renderers/WebGLMultisampleRenderTarget) so the samples on the context are expected to be 0.

The jaggies in your screenshot look more like low depth precision now that I think about it 🤔

**Comment by arpu** [comment]
ok looks like this is a chrome bug tested with latest dev Chrome on Linux with vulcan Render and this looks good
![Bildschirmfoto von 2021-03-25 21-13-36](https://user-images.githubusercontent.com/14173/112537529-166d7f00-8daf-11eb-8122-9e62f3ace5ad.png)
