### ISSUE TITLE
Gaphical glitch when using SMAA on 2 scenes at once

### ISSUE THREAD

**Issue by bendxr** [vanruesc/postprocessing#301]
Hi, 

I have 2 scenes : scene A : lots of objects + postprocessing effects, scene B : 1 object, fixed camera, only SMAA.
But the object on scene B, although antialiased, disappears progressively (except the edges) when rotating (if it's static, the problem won't raise).
In my project the object in scene B is textured, but the problem is exactly the same.

You can find the issue here : https://codesandbox.io/s/postprocessing-forked-3uufk

(derived from a codesandbox you did about a similar issue few months ago).

Expected behavior is to have SMAA applied on both scenes, without having object on scene B disappearing.

Have you any clue about what is doing wrong ?

Best regards,

**Comment by vanruesc** [comment]
This happens due to a dirty depth buffer. The effect composer swaps the internal frame buffer at certain times which leads to this behaviour. The first frame actually renders correctly, but all subsequent render calls are corrupted by the depth written by the cube. You can fix this by clearing depth before rendering the cube. See line 115-116:
https://codesandbox.io/s/postprocessing-forked-9pi8g?file=/src/App.js

You could also disable `depthWrite` and/or `depthTest` for the cube. Please note that depth-based SMAA wouldn't work in this case due to the dual scene setup and intermediate depth clearing.

**Comment by bendxr** [comment]
Hi, 
Many thanks for your kind explanation. It's working now on my side.

Would it be more effective if I would use either one or the other alternative : 
- use of Selection/layers instead of 2 distinct scenes (just like in https://codesandbox.io/s/gracious-kepler-ktfve?file=/src/App.js) ?
- render scene B onto a texture (with SavePass), render scene A, effects pass (bloom, ...), TextureEffect pass of texture from previous scene B rendering, and then apply SMAA at last ?

Best regards,

**Comment by vanruesc** [comment]
- Disabling `depthWrite` and `depthTest` is likely the most efficient solution, but it only works if `sceneB` doesn't need depth.
- Clearing depth isn't free but it's still very fast. This option allows `sceneB` to make use of depth if needed.
- Using layers is slightly less efficient than using two separate scenes, but it can make working with lights easier.
- Rendering `sceneB` to a texture and then mixing it in with a `TextureEffect` is the least efficient option as it requires an additonal buffer, but some use cases might require it.

**Comment by bendxr** [comment]
Many thanks for your clear explanations ! It helps a lot to better understand things... :+1: 

Best regards,
