### ISSUE TITLE
LUT problem in iOS 13 and below

### ISSUE THREAD

**Issue by Ben-Mack** [vanruesc/postprocessing#305]
In my own app, LUT on iOS <=13 appears quite a lot darker compared to iOS 14 or PC.
But I can't create a reproducable Codesandbox for that problem yet because my attempt don't even work on iOS 13.

The Color Grading example does not work on iOS <= 13:
![image](https://user-images.githubusercontent.com/6309393/126021977-c1d98216-09cd-491d-a6eb-d45b9bbdadb2.png)

Working fine on iOS 14:
![image](https://user-images.githubusercontent.com/6309393/126022179-31ba5394-5c07-4223-be89-c0e23d0a3d89.png)

___

I use this CodeSandBox to test LUT effect only (https://codesandbox.io/s/sparkling-water-99dle)
But it also doesn't work on iOS 13:
![image](https://user-images.githubusercontent.com/6309393/126022035-ebfffb44-bd03-4333-ba49-1640fbd4c790.png)
 
iOS 14 is fine too:
![image](https://user-images.githubusercontent.com/6309393/126022121-b220ab86-fd79-4ce1-975d-31f6df1843e5.png)

All the above problem only occurs on iOS 13 and below. 
iOS 14, PC, Android are fine.

( If you don't have the devices, you should use BrowserStack, it's really simple and free for open source contributor: https://www.browserstack.com/open-source )

**Comment by vanruesc** [comment]
Thanks for the report! I didn't know that BrowserStack offered this free option 👍 

I managed to track this issue down to this line: https://github.com/vanruesc/postprocessing/blob/4fb16005928bca1cb7f58649a49eb5cde8b6bae2/src/images/textures/LookupTexture3D.js#L212
It looks like iOS <= 13 doesn't like `Uint8ClampedArray`, but works just fine with `Uint8Array`: [sandbox](https://codesandbox.io/s/jolly-liskov-nwblg?file=/src/App.js)
I'll publish a patch in a bit.

> The Color Grading example does not work

The error regarding the "unexpected semicolon" in the demo is caused by [field declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#field_declarations) which are generated by esbuild. It looks like the demo build currently uses the default target `esnext` which needs to be changed to `es6`.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.22.2`.

**Comment by Ben-Mack** [comment]
Thanks for the quick fix!

The color grading example is working now, but the sandbox you provided is still throwing errors on iPhone XS iOS 13:
![image](https://user-images.githubusercontent.com/6309393/126059334-3af75ead-ce79-4795-85b5-3bd30b45f9f4.png)

**Comment by vanruesc** [comment]
> The color grading example is working now, but the sandbox you provided is still throwing errors on iPhone XS iOS 13:

Well, that's strange. Even removing the `LUTEffect` doesn't fix the errors. I randomly commented out the line `renderer.setPixelRatio(window.devicePixelRatio);` and that somehow fixed it. The strange thing is that the color grading demo [also sets the pixel ratio](https://github.com/vanruesc/postprocessing/blob/0782f850b02a12031361caedf1cb231413df6356/demo/src/index.js#L95) and works fine 🤷

Here's the updated sandbox : https://codesandbox.io/s/jolly-liskov-nwblg
