### ISSUE TITLE
Differences between RenderPass.depth and DepthPass

### ISSUE THREAD

**Issue by swingingtom** [vanruesc/postprocessing#330]
Hi, Im not sure this is a bug, but as I didn't find any information in documentation or in existing issues, I create one.

### Description of the bug
`DepthPass` doesn't produce the same results as `RenderPass+DepthSavePass`.
`DepthPass` seems to ignore : `material.depthWrite=false` , `material.side` , `material.alpha|material.alphaTest` 

### To Reproduce
Compare the results of both https://codesandbox.io/s/depthpass-vs-renderpass-depthsavepass-5bos0 
Toggle `DepthPass>>Show/Hide` from the gui to compare both depth 

### Expected behavior
Should'nt both ways produce the same results ?

### Screenshots
RenderPass
![image](https://user-images.githubusercontent.com/17314210/145678223-eb62dea4-533f-4ba2-8f9e-8961dcf14679.png)

Depth( from RenderPass )
![image](https://user-images.githubusercontent.com/17314210/145678240-86ba1aca-07fe-44b6-8f1b-39ce237293a6.png)

Depth( from DepthPass )
![image](https://user-images.githubusercontent.com/17314210/145678279-0853d2de-0d0c-4da7-bd22-26d0b68a90a5.png)

### Library versions used

 - Three: 0.132.2
 - Post Processing: 6.23.3

**Comment by vanruesc** [comment]
> DepthPass seems to ignore : material.depthWrite=false , material.side , material.alpha|material.alphaTest

That is correct; it's a limitation of three's [override material](https://threejs.org/docs/?q=scene#api/en/scenes/Scene.overrideMaterial) system. The `DepthPass` uses a `MeshDepthMaterial` to render the depth of objects into a render target. It ignores individual settings of the original materials for performance reasons.

The `RenderPass` + `DepthSavePass` combo works because the `DepthSavePass` enables an internal depth texture attachment for the `RenderPass`. The resulting depth is correct because all objects use their original materials, including [custom depth materials](https://threejs.org/docs/?q=mesh#api/en/core/Object3D.customDepthMaterial). The `DepthPass` ignores those too.

You can enable the [override material workaround](https://github.com/vanruesc/postprocessing/wiki/Skinned-and-Instanced-Meshes) which was primarily created to support skinned and instanced meshes. It supports the `side` parameter, but not `alphaTest`, `depthWrite`, and probably many other settings.

Trying to handle all possible values of built-in materials, not to mention custom shaders, is not feasible. The best solution is to use [MRT](https://threejs.org/docs/?q=mu#api/en/renderers/WebGLMultipleRenderTargets) instead, but it's a change that needs to happen in `postprocessing`, not in user code, and I'm working on it.

**Comment by swingingtom** [comment]
Hey ! Sorry for the super long delay.
Thank you for the answer. I was expecting such performance reasons. 

I could indeed adjust granularity of depth using available options `DepthPass` and `OverrideMaterial` workaround or simply rely on `DepthSavePass`.

I will therefore close this issue.

But is there any other differences? On the internal structure or something else? I tried to replace `DepthPass` with `DepthSavePass` in godrays example as explained here #331 but something works different, and I struggle to find what.

**Comment by iuriiiurevich** [comment]
> Trying to handle all possible values of built-in materials, not to mention custom shaders, is not feasible. The best solution is to use [MRT](https://threejs.org/docs/?q=mu#api/en/renderers/WebGLMultipleRenderTargets) instead, but it's a change that needs to happen in postprocessing, not in user code, and I'm working on it.

@vanruesc Are there any updates on this?

I ran into an issue when using `SelectiveBloomEffect` (which internally uses `DepthPass`) on meshes with `ShaderMaterial`, so the vertex shader is not being applied to the depth texture, resulting in a difference in vertex positions between objects on the screen and the bloom result (which is expected)

**Comment by vanruesc** [comment]
> Are there any updates on this?

@iuriiiurevich Progress has been made but #419 skipped over a lot of details that I need to figure out as I go. There will be a big commit in the next few days to establish the baseline for v7.
