### ISSUE TITLE
Doesn't work with three.js r80

### ISSUE THREAD

**Issue by rbozan** [vanruesc/postprocessing#44]
> three.js:11868 THREE.WebGLProgram: shader error:  1281 gl.VALIDATE_STATUS false gl.getProgramInfoLog invalid shaders  ERROR: 0:325: 'linearToOutputTexel' : no matching overloaded function found 
ERROR: 0:325: 'assign' :  cannot convert from 'const float' to 'FragColor mediump 4-component vector of float'

full error log:
https://gist.github.com/rbozan/af0476b234c266b059889a3c6db999c7

**Comment by vanruesc** [comment]
Thanks for the issue!

The error you described doesn't appear to be caused by this library. All demos work as expected with three.js r80.

My guess is that some kind of invalid input texture or encoding is involved. When three.js compiles a shader program, it checks the encoding of textures to find the correct conversion function.

This piece of code doesn't find the correct encoding in your case: https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLPrograms.js#L77
Consequently, this piece of code doesn't include the right shader function: https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLProgram.js#L478

One thing to be aware of is that it's important to use the `texture` property of input render targets.

Hope I could help!

**Comment by rbozan** [comment]
Hmm

I guess it was an error at my part but I can't find out what I have done wrong, but it seems to work now. I'll re-open this issue if this still happens. Thanks for your help anyways.

(ps: don't forget to `npm publish` ^^)

**Comment by vanruesc** [comment]
In the latest commits I didn't change any code either. If it works now, then that's good.

> (ps: don't forget to npm publish ^^)

Oops, I could've sworn I'd published it. My bad :)
