### ISSUE TITLE
ShaderPass documentation / help

### ISSUE THREAD

**Issue by chasevida** [vanruesc/postprocessing#57]
Hi there,

Relatively new to Threejs and find myself trying to add in my own shader to achieve a look. I've used the standard `THREE.ShaderMaterial` and got that working but I can't seem to get that working with this library and the effect composer. Assuming that's the expected behaviour I then tried to create a shader object and pass it to the `ShaderPass`. However, I'm totally stuck on how I should construct this as most of what I can gather you simply pass in the 'shader' i.e. `new ShaderPass(SomeShaderObject)` but that doesn't seem right (doesn't work either as far as I can see - but I am still learning this all).

How do I set this up so as to pass in the scene, camera etc. and have my shader used as part of the effect composer pipeline?

Cheers.

**Comment by vanruesc** [comment]
Hello!

The ```ShaderPass``` expects an instance of ```THREE.ShaderMaterial``` as its first argument. The second argument specifies the name of the texture sampler uniform of the shader you provide. This name defaults to ```tDiffuse``` because most shaders use that name. The ```ShaderPass``` binds the read buffer to this uniform.

Basically, you just have to pass your shader object (uniforms, defines, fragment and vertex shader code) to ```THREE.ShaderMaterial``` and then pass that material instance to ```ShaderPass``` and adjust the name of the input texture if necessary.

I prepared an example for you [here](https://jsfiddle.net/xjn8ucks/) which uses the [Kaleidoscope Shader](https://threejs.org/examples/js/shaders/KaleidoShader.js) from the three.js examples.

If something's still unclear, just ask!

**Comment by chasevida** [comment]
Thanks @vanruesc, much appreciated.

Just in case anyone else needs this:

```javascript
const myShaderMaterial = new THREE.ShaderMaterial({
  uniforms: {...}
  vertexShader: `...`,
  fragmentShader: `...`
})
const myShaderPass = new ShaderPass(myShaderMaterial)
composer.addPass(myShaderPass)
```
