### ISSUE TITLE
.shading has been removed. Use the boolean .flatShading instead.

### ISSUE THREAD

**Issue by Jeremboo** [vanruesc/postprocessing#60]
Hi,

I encountered a problem when I tried to add a pass with the three.js **rj86** version.

For example with the BloomPass : 

```javascript
const bloomPass = new BloomPass({
  resolutionScale: 0.5,
  intensity: 2.0,
  distinction: 4.0,
});
```
```
THREE.LuminosityMaterial: .shading has been removed. Use the boolean .flatShading instead.
THREE.ConvolutionMaterial: .shading has been removed. Use the boolean .flatShading instead.
THREE.CombineMaterial: .shading has been removed. Use the boolean .flatShading instead.
```

I also tried the BlurPass and I have overall the same error.

version: postprocessing@2.3.1

**Comment by vanruesc** [comment]
Hallo!

your issue might be caused by misconfigured dependencies.

`.shading` has been replaced with `.flatShading` in three.js __r87__ ([related PR](https://github.com/mrdoob/three.js/pull/11724)). If you're really using __r86__ as you say, then you shouldn't even see this particular deprecation warning. Also note that `postprocessing@2.3.1` is intended to be used with `three.js@0.87.x`, but it should still work just fine with earlier versions of three.js.

Moreover, the postprocessing library doesn't set `.shading` or `.flatShading` anywhere in the code base. Only some of the demos use this setting and those have been updated in 30c9622.

Without more information, I'm afraid I can't help you. You could try to delete all dependencies in your project and reinstall with `npm install`. Sometimes things get tangled up.

**Comment by Jeremboo** [comment]
Switch to **r87** solves the problem !

But where are not reason to have this problem in **r86**...
Maybe the three.js version on your library take the top on mine.

Thank for your time !
