### ISSUE TITLE
Outline Pass

### ISSUE THREAD

**Issue by JakeDluhy** [vanruesc/postprocessing#64]
In the THREE.js examples there's an outline pass example that I want to use. Would you accept a PR with it (If I updated it toyour current code style, etc...)?

**Comment by vanruesc** [comment]
Hi Jake,

it'd be great if you could send a PR for that!

The `OutlinePass` is one of the missing passes that I haven't gotten around to including yet due to lack of time. In fact, I'm also still planning on including the `GodRaysPass` and `SAOPass` from the `three.js` examples as well as some passes from `Wagner` and a couple other effects from other sources.

**Comment by vanruesc** [comment]
FYI: I've updated the [contribution guidelines](https://github.com/vanruesc/postprocessing/blob/master/CONTRIBUTING.md) with some more information about the available development build tasks and how to run the demo locally for testing purposes.

**Comment by vanruesc** [comment]
The `OutlinePass` is now included in `postprocessing@4.2.0`.

If there's an issue with this pass, please let me know in a new ticket 😄
