### ISSUE TITLE
Question: Why you use #define to define a function ? What's the different ?

### ISSUE THREAD

**Issue by scarletsky** [vanruesc/postprocessing#83]
Hi, thanks for your great job!
I am learning SMAA and diving into the source code of it.
In  `smaa-weights/shader.frag`, there is a line:

```glsl
#define sampleLevelZeroOffset(t, coord, offset) texture2D(t, coord + float(offset) * texelSize, 0.0)
```

I don't know the different between `#define sampleLevelZeroOffset` and `vec4 sampleLevelZeroOffset(...)`.
Could you tell me more about this ?
Thanks !

**Comment by vanruesc** [comment]
Hi,

that's a preprocessor macro definition. Macros are no true functions and only serve as placeholders. When the shader code is compiled by the WebGL compiler, all occurances of `sampleLevelZeroOffset(t, coord, offset)` will be replaced by `texture2D(t, coord + float(offset) * texelSize, 0.0)`.

The main benefit of using macros like these is to reduce code repitition.

There are other uses for custom macros, too. For instance, the [original SMAA code](https://github.com/iryoku/smaa/blob/master/SMAA.hlsl#L526) heavily relies on macro definitions to handle different shader languages in a single universal shader.

Since you're looking into the SMAA code please note that the SMAA shaders in this library are missing some interesting features such as advanced diagonal pattern detection and corner rounding. Porting these features to WebGL requires a more in-depth understanding of the original algorithms.

**Comment by scarletsky** [comment]
Hmm, I am a bit confused.  The macro was defined as:

```
sampleLevelZeroOffset(t, coord, offset)
```

But used it as:

```
sampleLevelZeroOffset(tDiffuse, coords, ivec2(1, 0))
```

They are not the same. Does the preprocessor can replace `t` with `tDiffuse` and replace `offset` with `ivec2(1.0)`?

**Comment by vanruesc** [comment]
> They are not the same. Does the preprocessor can replace t with tDiffuse and replace offset with ivec2(1.0)?

Yes, the compiler does exactly that. It also replaces `coords` with `coords` 😄 

The GLSL preprocessor directives are pretty much the same as the standard C set of preprocessor directives. If you need more information, you could check out the [C macro documentation](https://gcc.gnu.org/onlinedocs/cpp/Macros.html#Macros) and the relevant [function-like macro section](https://gcc.gnu.org/onlinedocs/cpp/Function-like-Macros.html#Function-like-Macros).

**Comment by scarletsky** [comment]
@vanruesc Thank you for your help ! 😃
