### ISSUE TITLE
GodRays parameters not used by the pass class

### ISSUE THREAD

**Issue by Thibka** [vanruesc/postprocessing#90]
I'm running some tests with the GodRays pass. The demo (https://vanruesc.github.io/postprocessing/public/demo/#god-rays) provides a lot of parameters like density, decay, weight, etc. which are actually present in the class constructor comments. 
`export class GodRaysPass extends Pass {

	/**
	 * Constructs a new god rays pass.
	 *
	 * @param {Scene} scene - The main scene.
	 * @param {Camera} camera - The main camera.
	 * @param {Object3D} lightSource - The main light source.
	 * @param {Object} [options] - The options.
	 * @param {Number} [options.density=0.96] - The density of the light rays.
	 * @param {Number} [options.decay=0.93] - An illumination decay factor.
	 * @param {Number} [options.weight=0.4] - A light ray weight factor.
	 * @param {Number} [options.exposure=0.6] - A constant attenuation coefficient.
	 * @param {Number} [options.clampMax=1.0] - An upper bound for the saturation of the overall effect.
	 * @param {Number} [options.intensity=1.0] - A constant factor for additive blending.
	 * @param {Number} [options.resolutionScale=0.5] - The render texture resolution scale, relative to the screen render size.
	 * @param {Number} [options.kernelSize=KernelSize.LARGE] - The blur kernel size.
	 * @param {Number} [options.samples=60] - The number of samples per pixel.
	 * @param {Number} [options.screenMode=true] - Whether the screen blend mode should be used for combining the god rays texture with the scene colors.
	 */`

But some of them have no effect, since they don't seem to be actually used by the class.
These 'ghost' parameters are:
- density
- decay
- weight
- exposure
- clampMax
There is also a blurriness parameter in the demo which isn't in the class. 

Am I missing something?

**Comment by vanruesc** [comment]
> But some of them have no effect, since they don't seem to be actually used by the class.

The `GodRaysPass` constructor passes the `options` object to its internal [BlurPass](https://github.com/vanruesc/postprocessing/blob/master/src/passes/GodRaysPass.js#L163) and [GodRaysMaterial](https://github.com/vanruesc/postprocessing/blob/master/src/passes/GodRaysPass.js#L198). The parameters are repeated in the `GodRaysPass` constructor documentation for convenience.

The parameters you mentioned are used [here](https://github.com/vanruesc/postprocessing/blob/master/src/materials/GodRaysMaterial.js). They should have an effect. Please make sure that the parameters are spelled correctly since that's a common pitfall with map-like parameters. If you're still having trouble, you could provide a small jsfiddle that illustrates the issue.

> There is also a blurriness parameter in the demo which isn't in the class.

That option is just an alias for the [BlurPass](https://github.com/vanruesc/postprocessing/blob/master/src/passes/BlurPass.js#L141)'s [KernelSize](https://github.com/vanruesc/postprocessing/blob/master/src/materials/ConvolutionMaterial.js#L120).

I hope this helps!

**Comment by Thibka** [comment]
You're right, and once again very helpful.
I was actually trying to modify these parameters dynamically from the console, I understand now why this can't be done. If I pass the parameters to the constructor when creating the instance, everything works as expected.
Thanks!
