### ISSUE TITLE
OutlineEffect doesn't work

### ISSUE THREAD

**Issue by ktlshy** [vanruesc/postprocessing#97]
I try to use the outlineEffect, but it doesn't work，and there is no error or other useful info about it.
Can someone give me some help?
```javascript
  initPostprocess() {
    this.composer = new EffectComposer(this.view.renderer, {
      stencilBuffer: true
    });
    this.renderPass = new RenderPass(this.world.scene, null);
    this.renderPass.renderToScreen = true;

    this.outlineEffect = new OutlineEffect(
      this.world.scene,
      this.viewer.camera,
      {
        edgeStrength: 10,
        pulseSpeed: 0.0,
        visibleEdgeColor: 0xffffff,
        hiddenEdgeColor: 0x22090a,
        blur: false,
        xRay: true
      }
    );
    this.outlinePass = new EffectPass(this.viewer.camera, this.outlineEffect);
    this.renderPass.renderToScreen = false;

    const mesh = new Mesh(
      new BoxBufferGeometry(1, 1, 1),
      new MeshPhongMaterial({
        color: 0x00ffff
      })
    );
    this.world.addObject(mesh);
    this.outlineEffect.setSelection([mesh]);
    this.composer.addPass(this.outlinePass);
  }

 update(delta) {
    this.composer.render(delta);
  }
```

**Comment by vanruesc** [comment]
Hi,

there are a few minor issues with your setup. The code you've given should fail with the error message `THREE.WebGLRenderer.render: camera is not an instance of THREE.Camera` because you don't provide your `RenderPass` with a camera. The reason why you're not seeing this error is because you never add the `RenderPass` to the composer.

Fixing these two issue will still leave you with a black screen because none of your passes is configured to render to screen. Remove `this.renderPass.renderToScreen = true;` in line 6 and replace line 21:
`this.renderPass.renderToScreen = false;` &rarr; `this.outlinePass.renderToScreen = true;`

Here's a working example: [Outline Effect](https://jsfiddle.net/jbq91eah/)

Also note that you don't need to activate the `stencilBuffer` unless you plan on using a `MaskPass` or a custom pass in which you modify stencil bits.

If something's still unclear, feel free to ask!

**Comment by ktlshy** [comment]
Thank you very much for your detailed answer and example. It works。🍻
